# Generated by Django 4.1.5 on 2023-01-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_note_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
