# Generated by Django 4.1.5 on 2023-01-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_note_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'заметка', 'verbose_name_plural': 'заметки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
