# Generated by Django 4.1.5 on 2023-01-13 04:21

from django.db import migrations, models
from django.utils.datetime_safe import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_note_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('created_at',), 'verbose_name': 'заметка', 'verbose_name_plural': 'заметки'},
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('alert_send_at__gte', datetime(2022, 1, 1, 0, 0)), ('alert_send_at__isnull', False)), ('alert_send_at__isnull', True), _connector='OR'), name='alert_send_at_after'),
        ),
    ]
