# Generated by Django 4.1.5 on 2023-01-13 05:08

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.get_note_image_path, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=web.models.get_note_file_path, verbose_name='Файл'),
        ),
    ]
