# Generated by Django 4.1.5 on 2023-01-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('staff', 'Сотрудник'), ('user', 'Пользователь')], default='user', max_length=15),
        ),
    ]
