# Generated by Django 4.1.5 on 2023-01-13 05:20

from django.db import migrations
import stdimage.models
import src.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_note_image_alter_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=src.web.models.get_note_image_path, variations={'thumbnail': {'height': 200, 'width': 200}}, verbose_name='Картинка'),
        ),
    ]
